name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: try just ubuntu main universe
        run: |
          sudo mv /etc/apt/sources.list.d/microsoft-prod.list /etc/apt/sources.list.d/microsoft-prod.list.0
          sudo mv /etc/apt/sources.list.d/azure-cli.sources /etc/apt/sources.list.d/azure-cli.sources.0
          sudo perl -pi -e 's/Components: main universe restricted multiverse/Components: main universe/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get clean
      - name: update ubuntu main+universe
        run: |
          sudo apt-get update
      - name: list ubuntu main+universe
        run: |
          sudo apt-cache search . > ubuntu.main-universe.list
      - name: upload lists
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: .
