name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: normal update
        run: |
          sudo apt-get update
      - name: list all
        run: |
          sudo apt-cache search . > ~/github.full.list
      - name: try just ubuntu
        run: |
          sudo mv /etc/apt/sources.list.d/microsoft-prod.list /etc/apt/sources.list.d/microsoft-prod.list.0
          sudo mv /etc/apt/sources.list.d/azure-cli.sources /etc/apt/sources.list.d/azure-cli.sources.0
          sudo apt-get clean
      - name: update ubuntu
        run: |
          sudo apt-get update
      - name: list ubuntu
        run: |
          sudo apt-cache search . > ~/ubuntu.full.list
      - name: try just microsoft
        run: |
          sudo mv /etc/apt/sources.list.d/microsoft-prod.list.0 /etc/apt/sources.list.d/microsoft-prod.list
          sudo mv /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.0
          sudo apt-get clean
      - name: update microsoft
        run: |
          sudo apt-get update
      - name: list microsoft
        run: |
          sudo apt-cache search . > ~/microsoft.base.list
      - name: try just azure
        run: |
          sudo mv /etc/apt/sources.list.d/azure-cli.sources.0 /etc/apt/sources.list.d/azure-cli.sources
          sudo mv /etc/apt/sources.list.d/microsoft-prod.list /etc/apt/sources.list.d/microsoft-prod.list.0
          sudo apt-get clean
      - name: update azure
        run: |
          sudo apt-get update
      - name: list azure
        run: |
          sudo apt-cache search . > ~/azure.base.list
      - name: try just ubuntu main
        run: |
          sudo mv /etc/apt/sources.list.d/azure-cli.sources /etc/apt/sources.list.d/azure-cli.sources.0
          perl -pe 's/Components: main universe restricted multiverse/Components: main/' /etc/apt/sources.list.d/ubuntu.sources.0 | sudo tee /etc/apt/sources.list.d/ubuntu.sources > /dev/null
          sudo apt-get clean
      - name: update ubuntu
        run: |
          sudo apt-get update
      - name: list ubuntu main
        run: |
          sudo apt-cache search . > ~/ubuntu.main.list
      - name: upload lists
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: .
